# Generated by Django 5.2 on 2025-04-14 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('name', 'specialization', 'created_by')},
        ),
    ]
